---
title: "Actividades transversales"
number-sections: false
---

## Actividad 1. Monitoreo de la Gestión {.unnumbered.}

### 1.1 Monitoreo de la Gestión

Este trimestre, se realizó una reunión de trabajo con el equipo del área de información, la Dirección de Monitoreo y Planificación, y la Dirección de Desarrollo Insitucional e Investigaciones. El objetivo fue de explicar el flujo de trabajo de Acuerdos de Conservación y Fondo Semilla, así como organizar las tablas de datos que se utilizan, para sistematizar mejor los reportes y realizar el seguimiento de las actividades ([Anexo 1.1 - informe](https://drive.google.com/drive/folders/12eYlU1iPqX-fgP7Ny1D1zFGZD5H8f5AZ?usp=sharing))

### 1.2 Creac.Opinión Publ.Favorable PNCAZ

**Coordinación de actividades con AIDER.** La coordinación de la sede Aguaytía participó de una reunión de socialización por invitación del equipo de AIDER. Este presentó su nuevo responsable Zonal de Padre Abad, Joel Mananita Urquia. Además, informaron de su programa "Bosques vivos para siempre" su modo de trabajo y las actividades que vienen desarrollando en las comunidades que tienen intervención. A su vez, CIMA informó de las actividades que desarrolla con las comunidades, en la ZA y dentro del PN Cordillera Azul, especialmente con las comunidades donde AIDER y CIMA desarrollan proyectos, en común. Otras instituciones también informaron las actividades que vienen realizando como el Ing. Edgardo Miranda Ruiz, de la Agencia Agraria que agradeció el apoyo de CIMA con la donación de plantones para el cumplimiento de sus actividades.

**Reunión informativa con DEVIDA.** La coordinación de la sede Tarapoto; en representación del director (e) del programa participó en una reunión informativa con representantes de DEVIDA. Se intercambió información de los ámbitos de intervención y los procesos que CIMA está implementado. El objetivo fue coordinar acciones conjuntas, en áreas de intervención común. DEVIDA se ha comprometido ha compartir información más detallada, en una próxima reunión.

**Celebrando a los Pueblos Indígenas en ailsamiento y contacto inicial (PIACI).** Se participó en el evento "Presta tu voz a los PIACI" que se realizó en la Plaza Mayor de Aguaytía. Participaron diversas instituciones como la Federación Nativa de Comunidades Kakataibo, Instituto del Bien Común, Municipalidad Provincial de Padre Abad, AIDESEP, entre otros. El evento tuvo como finalidad, que la población conozca y se haga visible la existencia de los Pueblos Indígenas en situación de Aislamiento y Contacto Inicial -- PIACI. La sede Aguaytía-CIMA, resaltó la importancia de la existencia de los PIACI, ya que parte de ellos viven en armonía dentro del Parque Nacional Cordillera Azul y su Zona de Amortiguamiento.

Además, se contó con a la presentación de raperos de la etnia Shipibo -- Conibo, la cantante Ruth Katina y la presencia del influencer Gianmarco Moreno. Finalmente se presenció el video: "Grompes, Curumi y la niña de la papaya" Cabe señalar que, esta actividad fue realizada por el Instituto del Bien Común -- IBC y la Federación Nativa de Comunidades Kakataibos -- FENACOKA.

**Presentación del proyecto "Restauración del Paisaje Forestal".** En febrero del presente año, en el auditorio de hotel Costa del Sol, Pucallpa, se participó en la presentación del proyecto "Restauración del Paisaje Forestal en la Amazonia Peruana" de la empresa ***Form International Peru y Forma International Holanda***. El proyecto en mención contempla dos componentes: 1, Plantación en núcleo y el 2, Programa con productores locales. Este proyecto se está ejecutando en el distrito de Campo Verde, provincia de Coronel Portillo -- región Ucayali.

**Reunión informativa con la empresa Swisscontact.** En marzo, se realizó una reunión con los representantes de la empresa Swisscontact, Fundación Suiza de Cooperación para el Desarrollo Técnico. El director del Programa de CIMA, Lorenzo Yzquierdo, expuso sobre la gestión del PNCAZ. El señor Alex Llanos de Swisscontact mencionó que ejecutarán un proyecto con enfoque de paisaje sostenible, en el corredor Tingo María-Pucallpa con fondos propios. El periodo del proyecto será de 4 años (2025-2028); actualmente se está elaborando el proyecto e identificando instituciones para hacer sinergias. El proyecto a desarrollar estará relacionado a actividades productivas sostenibles, turismo, artesanías, entre otros.

**Apoyo en la articulación de necesidades.** En el mes de febrero, la Comunidad Nativa Kichwa de Chipeza solicitó la participación de CIMA en una reunión informativa, con la finalidad de indicar el ámbito de intervención de CIMA en la ZA respecto del PN Cordillera Azul. La comunidad ha solicitado el apoyo de CIMA para articular con otras dependencias del estado, para que puedan solicitar y atender sus necesidades. La comunidad nativa de Chipeza, se encuentra ubicada a la margen izquierda del río Huallaga, en el distrito de Chazuta. La primera comunicación recibida por CIMA, fue una solicitud de la comunidad para dar apoyo en el establecimiento de señalética y letreros del perímetro de su territorio comunal. Producto de esta reunión, se desarrollo una reuniòn con el ACR Cordillera Escalera y la municipalidad de Chazuta, para apoyar en la identificación y georreferenciación de los puntos críticos en el perímetro del territorio comunal. CIMA, está apoyando parte de las actividades logísticas.

**Apoyo en actividades comprometidas con la gestión del parque.** A petición de los directivos del colectivo Chuya Chuya y de la municipalidad de Chazuta, se realizó una reunión para coordinar actividades a desarrollar en el manejo de residuos sólidos y el desarrollo de una planta de valorización. La Municipalidad del distrito elaborará una ficha técnica con los detalles para la construcción de la planta, que será entregado a CIMA-SERNANP para definir el apoyo que brindar

**Representación institucional en el día del artesano.** En el mes de marzo se atendió una invitación de la Municipalidad del distrito de Chazuta. CIMA participó en las actividades conmemorativas por el día del artesano; actividad que permite resaltar la importancia para la preservación de la cultura del distrito y el trabajo que los artesanos desarrollan.

**Apoyo en la elaboración de una guía de planes de calidad de vida.** En el mes de marzo y atendiendo la invitación de la CODEPISAM, se ha participado de un taller para la revisión de la actualización de una guía para la elaboración de planes de vida en comunidades nativas de la región. Actividad que cuenta con el apoyo técnico y financiero del MINAM, a través del Programa Nacional de Conservación de Bosques. En el taller, CIMA sugirió que la metodología propuesta por los consultores, no propicia la reflexión de las comunidades en el proceso de construcción de su plan de vida, consideramos que la propuesta es una metodología en donde prima lo técnico, por lo que se sugirió que los planes de vida deben ser el producto de un proceso reflexivo y de construcción social de las propias comunidades.

### 1.5 Fortalecimiento Interno

**Manipulación y aplicación de suero antiofídico e inyectables generales, en la sede Tarapoto.** Se ha desarrollado una jornada de capacitación dirigido al equipo técnico de campo, para la correcta aplicación de inyectables, así como la adecuada manipulación y aplicación de sueros antiofídicos. En esta jornada, también participó el personal administrativo de la sede, así como los especialistas de jefatura. La capacitación fue dirigida por dos profesionales del área de salud, con amplia experiencia en el tema.

**Capacitación en primeros auxilios, en la sede Tocache.** Se realizo una capacitación de Primeros auxilias para el equipo de campo guardaparque y técnicos. La capacitación fue realizada por el personal de Hospital de Tocache; los cuales explicaron el procedimiento y atenciones que el personal de tener frente a los accidentes ofídicos y mordedura de arañas; como los primeros auxilios, intoxicaciones o envenenamiento. Primeros auxilios en mordedura de araña ([Anexo actividad 1.5 - ver informe](https://drive.google.com/drive/folders/1XNl67dkUJByxpLL1Joa2FNpVbT6Av93d?usp=sharing)).

### 1.9 Asesoría Legal tema Kichwas

::: callout-warning
## Actividad no programada este trimestre.
:::

## Actividad 2. Participación en Plataformas y Mesas Técnicas

Participación en el taller macro regional para la actualización de la Estrategia Nacional de Diversidad Biológica, organizado por el MINAM, y en donde se han socializado los indicadores que permitirán medir los avances en la implementación de la estrategia en mención.

Participación en la primera reunión ordinaria de la Comisión Ambiental regional de San Martín, en donde la secretaría técnica de esta plataforma ha socializado los avances en la implementación de los diferentes instrumentos de gestión ambiental de la región. Por nuestra parte, solicitamos la reactivación de los grupos técnicos conformados al interior de la CAR, así como la descentralización de las reuniones, con la finalidad de asegurar la participación de los demás actores de la región. La solicitud fue aceptada, y en una reunión virutal, se dejó de manifiesto la intención de CIMA, de continuar en la coordinación del grupo técnico de restauración ecológica. Adicionalmente, se propuso que cada uno de los grupos, en la comisión ambiental, debería proponer un plan de trabajo a implementarse en el transcurso del año.

**Comisión ambiental Municipal-Tocache.** Se socializó a la CAM los resultados del inventario local de gases de efecto invernadero, en marco a la formulación del Plan local de Cambio Climático, de la provincia de Tocache. Producto de esta reunión se acordó elaborar un análisis de riesgo, de la provincia, para la formulación de las medidas de adaptación al cambio climático. CIMA se ha comprometido con el ARA San Martín a desarrollar reuniones de trabajo, para este fin ([Anexo actividad 2.1](https://drive.google.com/drive/folders/1Kb9g65qNkZHOzG6VHACsIiPh_gdZVmIE?usp=sharing)).

### 2.1. Participación en eventos científicos y otros espacios de divulgación

Las áreas técnicas de información y SIG de CIMA, están desarrollando trabajos sobre los registros de fauna, socio-ecológicos y vigilancia remota, con miras a la presentación de trabajos de investigación en el congreso de Investigaciones en ANPs, en octubre 2024.

## Actividad 3. Difusión y diseminación de experiencias

### 3.1 Comunicación del Programa

Durante el primer trimestre del 2024, el equipo de comunicaciones e incidencia pública de CIMA se centró en anunciar a los ganadores del fondo concursable "Emprendedores por Cordillera Azul", y en coordinar el lanzamiento de la segunda edición del concurso "Emprendedores por Naturaleza -- Parque Nacional Cordillera Azul", en colaboración con el Sernanp. Además, se dio inicio a la elaboración del [Plan de Comunicaciones e Incidencia Pública de CIMA]{.smallcaps} y a la Estrategia de Comunicaciones del PNCAZ. Estos procesos se fortalecieron con reuniones internas con las sedes regionales de Aguaytía, Contamana, Tarapoto y Tocache, así como con la Jefatura del PNCAZ y Comunicaciones del SERNANP.

Por otro lado, el equipo de comunicaciones se ha encargado del seguimiento y recolección de información para la presentación y envío del segundo reporte del proceso de implementación de la Hoja de Ruta (HdR) sobre Criterios de Ambiente, Sostenibilidad y Gobernanza (ASG) y Derechos Humanos para el Proyecto REDD+ del Parque Nacional Cordillera Azul, consensuado entre CIMA y Total Energies Nature-Based Solutions (TENBS), desde una perspectiva de comunicación estratégica e incidencia pública.

Se ha continuado con la difusión de actividades de difusión de los procesos sociales que se realizan en el parque y la ZA. La producción de notas, diseños, audios, desarrollados este trimestre, se detallan en el [Anexo 3.1](https://drive.google.com/drive/folders/1P4cuaNti8Mr3EhxObgTN_546pltsmqvG?usp=drive_link).
