name: Deploy Quarto Site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'

      - name: Install Quarto
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.0/quarto-v1.4.0-linux-amd64.deb
          sudo dpkg -i quarto-v1.4.0-linux-amd64.deb

      - name: Build with Quarto
        run: quarto render _quarto.yml --output-dir _docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _docs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

